### ISSUE TITLE
Error sending email (from dv@dv.com to dmtit6@gmail.com with reply-to 1).

### ISSUE THREAD

**Issue by dmiric** [dreamfony/dv#69]
Exception occurred while trying to send test email from dv@dv.com to dmtit6@gmail.com. 0: Error (4) when trying to json_decode response.                                                           
Error sending email (from dv@dv.com to dmtit6@gmail.com with reply-to 1).

**Comment by 0xCardiE** [comment]
We need to update both library to 2.4 and modul to beta and this will be resolved, current versions do not match. 

Probably @dmiric will handle this in main branch.
