### ISSUE TITLE
As a PO I want to decommission Trello, so I can stop thinking about it.

### ISSUE THREAD

**Issue by dmiric** [dreamfony/dv#79]
- [x] Remove Slack integration
- [x] Move relevant tasks and stories to Idea inbox
- [x] Add relevant people to github

**Comment by dreamfony** [comment]
Trello Board which was used for tracking software dev is closed.
One general DMT-IT board was created https://trello.com/b/w8yAHiLJ/dmt-it
It will be used by non developers for things like organizing Meetups etc. and general Ideas.
