### ISSUE TITLE
As a TM I want to know the content of a meeting, so I can be in the loop.

### ISSUE THREAD

**Issue by dmiric** [dreamfony/dv#86]
- [x] Research solutions for recording Hangouts calls
- [x] Create a template for writing a clear summary of a meeting, with keynotes and recorded call

**Comment by dreamfony** [comment]
Send message to Slack when Meeting recording is uploaded to Recordings Folder

@adriadrop Ako misliš da ima potrebe tu nešto nadodati
https://docs.google.com/document/d/1hyE0EopvlE0TIZUGbXHm8hyKudtxm8Mg2oriVLBsmqs/edit#heading=h.qyczcrxsszsg

**Comment by 0xCardiE** [comment]
I removed YT stream part from docs.

**Comment by 0xCardiE** [comment]
This part is missing explanation how.
"You can set up zoom.us Recording folder to save to folder that syncs automatically with Google Drive." @dreamfony ?

**Comment by 0xCardiE** [comment]
I added some info in it about sharing videos manually.

**Comment by dreamfony** [comment]
Added explanation. THX
